name: Sungwon Kim
description: 구글링 전문 개발자
meta_description: "구글링으로 다져가는 비전공자의 테크블로그"
email : "kpiswon@gmail.com"
github : "kpiswon"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15

baseurl: ""
domain_name: "https://kpiswon.github.io"
google_analytics: "UA-175844509-1"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://kpiswon.github.io"
author: "Sungwon Kim"

# Disqus config
disqus-shortname: ""

#여기서부터 내가 추가함
future : true
published : true
search : true
search_full_content : true
disqus_shortname: kpiswon
